name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy-storybook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Storybook to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: demo
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
