name: Publish

on:
  release:
    types: [published]

jobs:
  push-to-npm-registry:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for trusted publishing with OIDC
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
      # Ensure npm 11.5.1 or later is installed to be able to use trusted publishing
      - name: Update npm
        run: npm install -g npm@latest
      - name: Install
        run: npm ci
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish
        if: success()

  push-to-jsr:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for trusted publishing with OIDC
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Publish package
        run: npx jsr publish
